name: test

on:
  push:
    branches: [master]
  pull_request: null
  workflow_dispatch: null

env:
  FOUNDRY_PROFILE: ci

jobs:
  project:
    strategy:
      fail-fast: true

    name: Project
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge format check
        run: |
          forge fmt --check
        id: forge-check

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: forge-build

      - name: Run Trunk check
        uses: trunk-io/trunk-action@v1
        id: trunk-check

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: forge-test

      - name: Run Forge coverage
        run: |
          forge coverage --report lcov
        id: forge-coverage

      - name: Enforce minimum coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: lcov.info
          min_coverage: 80

      - name: Run Cargo build
        run: |
          cargo build --locked
        id: cargo-build

      - name: Run Cargo tests
        run: |
          cargo test --locked
        id: cargo-test
